### ISSUE TITLE
おうちスカウティングロゴ

### ISSUE THREAD

**Issue by 07JP27** [Scout-Association-of-Japan/SAJ-DownloadCenter#16]
## 改善詳細 / Details of Improvement
- おうちスカウティングロゴ追加。種類はTBD
   - メインロゴ（白背景・透過)
   - メインロゴwithコミュニケーションロゴ（白背景・透過)
   - スクエア
   - フレーム
   - 丸ロゴ

## 期待する見せ方・挙動 / Expected behavior
- トップページの「コミュニケーションロゴ」を「各種ロゴ」に改名してそこに並べる。

**Comment by caffisenna** [comment]
やります
