### ISSUE TITLE
画面サイズによってカードからタイトルがはみ出す場合がある

### ISSUE THREAD

**Issue by 07JP27** [Scout-Association-of-Japan/SAJ-DownloadCenter#4]
## 起こっている問題 / The Problem
- 画面サイズが1080pだとカードからタイトルがはみ出して表示される。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/11060273/76672033-6252e900-65dd-11ea-9b0f-ecabf91eb3fc.png)

## 期待する見せ方・挙動 / Expected Behavior
- タイトルがカード内に収まる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 1080pの画面でダウンロードセンターを開く
2. トップページのカードを確認する

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by caffisenna** [comment]
やります
