### ISSUE TITLE
ダウンロード前に規約に同意させる

### ISSUE THREAD

**Issue by 07JP27** [Scout-Association-of-Japan/SAJ-DownloadCenter#9]
## 改善詳細 / Details of Improvement
- 利用規約への同意を厳密に行う。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/11060273/76759548-3b5c0900-67cf-11ea-8ffa-e6a27db13db4.png)

## 期待する見せ方・挙動 / Expected behavior
- 図の通りに利用規約部分をダウンロードボタンの上に移動させる。
- ダウンロードを行うことにより「各種使用に関して」に同意したものとします。
→□「各種使用に関して」に同意します。　に変更。
- DLボタンはデフォルトで不活性
- チェックを入れると活性状態になる。

**Comment by caffisenna** [comment]
やります!
